Modify search
KaylaEcker/betsy pull request #49
Opened 2017-10-24 21:07 UTC by skwiens

- categories method in product model modified to only return categories associated with active products
- new method in merchants method to return a unique array of merchants with active products
- index product page changed so that user can only filter by active methods and active merchants

2017-10-24 21:21 UTC, vsawchuk requested changes
Once I edit a product to be retired, that works. But when I go back to the edit page, it defaults to an active status. We should use the current status to set the status on the edit form.

2017-10-24 21:21 UTC, vsawchuk commented on app/models/merchant.rb
> +    merchants = Product.where(status: "active").pluck(:merchant_id).uniq
nice!

2017-10-24 21:21 UTC, vsawchuk commented on test/models/product_test.rb
>    describe "self.retired_only" do
if we're removing the method, let's remove the tests too

2017-10-25 03:57 UTC, skwiens commented
Thanks! Made the changes...

2017-10-25 18:08 UTC, vsawchuk approved these changes

2017-10-25 18:08 UTC, merged